"use strict";
/**
 * Checkpoint Types
 *
 * Types for the checkpoint and recovery system.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DEFAULT_PRUNING_CONFIG = exports.WORKFLOW_STAGES = void 0;
exports.getStageByState = getStageByState;
exports.getStageByIndex = getStageByIndex;
/**
 * Standard workflow stages.
 */
exports.WORKFLOW_STAGES = [
    { index: 0, name: 'ingested', state: 'INGESTED', description: 'Context ingested from source' },
    { index: 1, name: 'patches_proposed', state: 'PATCHES_PROPOSED', description: 'Patches generated by agents' },
    { index: 2, name: 'awaiting_approval', state: 'WAITING_USER_APPROVAL', description: 'Waiting for user approval' },
    { index: 3, name: 'applying', state: 'APPLYING_PATCHES', description: 'Applying approved patches' },
    { index: 4, name: 'pr_open', state: 'PR_OPEN', description: 'Pull request opened' },
    { index: 5, name: 'verifying', state: 'VERIFYING_CI', description: 'Verifying CI checks' },
    { index: 6, name: 'done', state: 'DONE', description: 'Workflow completed successfully' },
];
/**
 * Get stage info by state.
 */
function getStageByState(state) {
    return exports.WORKFLOW_STAGES.find(s => s.state === state);
}
/**
 * Get stage info by index.
 */
function getStageByIndex(index) {
    return exports.WORKFLOW_STAGES.find(s => s.index === index);
}
/**
 * Default pruning configuration.
 */
exports.DEFAULT_PRUNING_CONFIG = {
    maxCheckpointsPerWorkflow: 10,
    maxCheckpointAgeDays: 30,
    keepFirstCheckpoint: true,
    preserveManualCheckpoints: true,
};
//# sourceMappingURL=checkpoint-types.js.map