/**
 * Checkpoint Types
 *
 * Types for the checkpoint and recovery system.
 */

// ============================================================================
// Checkpoint Core Types
// ============================================================================

/**
 * A workflow checkpoint - a snapshot of workflow state at a point in time.
 */
export interface Checkpoint {
  /** Unique checkpoint ID */
  id: string;

  /** The workflow this checkpoint belongs to */
  workflowId: string;

  /** Descriptive name */
  name: string;

  /** Workflow state at checkpoint time */
  state: string;

  /** Stage index (0-based) */
  stageIndex: number;

  /** Human-readable stage name */
  stageName: string;

  /** Full state snapshot */
  snapshot: CheckpointSnapshot;

  /** Optional metadata */
  metadata?: CheckpointMetadata;

  /** Whether this was created automatically */
  isAutomatic: boolean;

  /** When the checkpoint was created */
  createdAt: Date;

  /** Who created the checkpoint (for manual checkpoints) */
  createdBy?: string;
}

/**
 * Full state snapshot stored in a checkpoint.
 */
export interface CheckpointSnapshot {
  /** Current workflow state */
  workflowState: string;

  /** Base SHA at checkpoint time */
  baseSha?: string;

  /** Artifact summaries (not full content) */
  artifacts: ArtifactSummary[];

  /** PatchSet summaries */
  patchSets: PatchSetSummary[];

  /** Approval records */
  approvals: ApprovalSummary[];

  /** Recent event IDs */
  recentEventIds: string[];

  /** Current run status */
  lastRunId?: string;
  lastRunStatus?: string;

  /** Policy violations if any */
  hasViolations: boolean;
  violationCount: number;
}

/**
 * Artifact summary for checkpoint.
 */
export interface ArtifactSummary {
  id: string;
  kind: string;
  contentSha: string;
  createdAt: Date;
}

/**
 * PatchSet summary for checkpoint.
 */
export interface PatchSetSummary {
  id: string;
  title: string;
  status: string;
  patchCount: number;
  createdAt: Date;
}

/**
 * Approval summary for checkpoint.
 */
export interface ApprovalSummary {
  id: string;
  kind: string;
  createdAt: Date;
}

/**
 * Checkpoint metadata.
 */
export interface CheckpointMetadata {
  /** Why this checkpoint was created */
  reason?: string;

  /** What triggered the checkpoint */
  trigger?: 'stage_complete' | 'manual' | 'before_risky_op' | 'scheduled';

  /** Duration of the stage that just completed */
  stageDurationMs?: number;

  /** Any notes from the user */
  notes?: string;
}

// ============================================================================
// Stage Definitions
// ============================================================================

/**
 * Workflow stages for checkpoint tracking.
 */
export interface WorkflowStage {
  index: number;
  name: string;
  state: string;
  description: string;
}

/**
 * Standard workflow stages.
 */
export const WORKFLOW_STAGES: WorkflowStage[] = [
  { index: 0, name: 'ingested', state: 'INGESTED', description: 'Context ingested from source' },
  { index: 1, name: 'patches_proposed', state: 'PATCHES_PROPOSED', description: 'Patches generated by agents' },
  { index: 2, name: 'awaiting_approval', state: 'WAITING_USER_APPROVAL', description: 'Waiting for user approval' },
  { index: 3, name: 'applying', state: 'APPLYING_PATCHES', description: 'Applying approved patches' },
  { index: 4, name: 'pr_open', state: 'PR_OPEN', description: 'Pull request opened' },
  { index: 5, name: 'verifying', state: 'VERIFYING_CI', description: 'Verifying CI checks' },
  { index: 6, name: 'done', state: 'DONE', description: 'Workflow completed successfully' },
];

/**
 * Get stage info by state.
 */
export function getStageByState(state: string): WorkflowStage | undefined {
  return WORKFLOW_STAGES.find(s => s.state === state);
}

/**
 * Get stage info by index.
 */
export function getStageByIndex(index: number): WorkflowStage | undefined {
  return WORKFLOW_STAGES.find(s => s.index === index);
}

// ============================================================================
// Recovery Types
// ============================================================================

/**
 * Options for restoring from a checkpoint.
 */
export interface RestoreOptions {
  /** Whether to keep events after the checkpoint */
  preserveEvents?: boolean;

  /** Whether to preserve newer artifacts */
  preserveArtifacts?: boolean;

  /** Whether to preserve newer PatchSets */
  preservePatchSets?: boolean;

  /** Reason for the restore */
  reason?: string;

  /** Who is initiating the restore */
  restoredBy?: string;
}

/**
 * Result of a restore operation.
 */
export interface RestoreResult {
  success: boolean;
  checkpointId: string;
  workflowId: string;
  restoredToState: string;
  restoredToStage: number;
  error?: string;
  restoredAt: Date;
  cleanedUp: {
    events: number;
    artifacts: number;
    patchSets: number;
    runs: number;
  };
}

// ============================================================================
// Pruning Configuration
// ============================================================================

/**
 * Configuration for checkpoint pruning.
 */
export interface PruningConfig {
  /** Maximum checkpoints to keep per workflow */
  maxCheckpointsPerWorkflow: number;

  /** Maximum age of checkpoints (in days) */
  maxCheckpointAgeDays: number;

  /** Whether to keep the first checkpoint always */
  keepFirstCheckpoint: boolean;

  /** Whether to keep manual checkpoints */
  preserveManualCheckpoints: boolean;
}

/**
 * Default pruning configuration.
 */
export const DEFAULT_PRUNING_CONFIG: PruningConfig = {
  maxCheckpointsPerWorkflow: 10,
  maxCheckpointAgeDays: 30,
  keepFirstCheckpoint: true,
  preserveManualCheckpoints: true,
};

/**
 * Result of a pruning operation.
 */
export interface PruneResult {
  workflowId: string;
  prunedCount: number;
  remainingCount: number;
  prunedCheckpointIds: string[];
}
